### ISSUE TITLE
Allow bulk insertion of certificate blocks

### ISSUE THREAD

**Issue by jvillalobos** [mozilla-services/amo-blocklist-ui#37]
We sometimes get certificate blocks for dozens of certs at a time, and we should make that as easy as possible to do.

**Comment by Natim** [comment]
Do you mean adding a button, ``Save and add a new`` or do you think of something else?

**Comment by jvillalobos** [comment]
Here's one [example of a big request](https://bugzilla.mozilla.org/show_bug.cgi?id=1155145#c0). I'm thinking a single input where I can enter something like:

> 
> MF8xCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMRQwEgYDVQQLEwtQYXJ0bmVycyBDQTEfMB0GA1UEAxMWR2xvYmFsU2lnbiBQYXJ0bmVycyBDQQ==
> BAAAAAABCfhiO+s=
> 
> MF8xCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMRQwEgYDVQQLEwtQYXJ0bmVycyBDQTEfMB0GA1UEAxMWR2xvYmFsU2lnbiBQYXJ0bmVycyBDQQ==
> BAAAAAABHhw1vwc=
> 
> MF8xCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMRQwEgYDVQQLEwtQYXJ0bmVycyBDQTEfMB0GA1UEAxMWR2xvYmFsU2lnbiBQYXJ0bmVycyBDQQ==
> BAAAAAABCFiEp9s=

And that will create all the entries that are needed.

**Comment by n1k0** [comment]
> I'm thinking of a single input

So that would be some large textarea where you could enter the whole list in the specified format, and the results would be added in the appropriate data structure. Also, when editing, this form field should convert the data structure into text formatted in the same input format.

This should be achievable by creating and registering a [custom widget component](https://github.com/mozilla-services/react-jsonschema-form#custom-widgets).

**Comment by n1k0** [comment]
Fixed by #94.
